name: BUILD-DEPLOY-SITE
on:
  push:
    branches: [ main ]

jobs:
  init-website-code:
    runs-on: self-hosted
    container:
      image: registry.aproton.tech/aproton/blog-dev:latest
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - name: InitEnv
        run: |
          touch ~/.ssh/known_hosts
          if [ "$(cat ~/.ssh/known_hosts | grep github.com)" == "" ]; then
            ssh-keyscan github.com >> ~/.ssh/known_hosts
          fi
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Update Code
        run: git submodule update --init
  build-website:
      - name: Build site files
        run: make render
  deploy-website:
    needs: build-website
    runs-on: self-hosted
    steps:
      - name: Deploy WebSite
        run: rm -rf /var/www/aproton/public && cp -rf public /var/www/aproton/