name: BUILD-DEPLOY-SITE
on:
  push:
    branches: [ main ]

jobs:
  build-website:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Update Code
        run: |
          if [ "$(cat ~/.ssh/known_hosts | grep github.com)" == "" ]; then
            ssh-keyscan github.com >> ~/.ssh/known_hosts
          fi
          git submodule update --init

      - name: Build site files
        run: make render
  deploy-website:
    needs: build-website
    runs-on: self-hosted
    steps:
      - name: Deploy WebSite
        run: rm -rf /var/www/aproton/public && cp -rf public /var/www/aproton/